#-------------------------------
# Site Settings
title: VJs Mag
description: Your source for the latest in vj technology and culture
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Latest"
      url: "/latest/"
    - title: "Authors"
      url: "/authors/"
    - title: "Videos"
      url: "/videos/"
    - title: "The Mag"
      submenu:
      - url: "/about/"
        title: "About"
      - url: "/partners/"
        title: "Partners"
      - url: "/advertise/"
        title: "Advertise"
      - url: "/documentation/"
        title: "Docs"
      - url: "/contact/"
        title: "Contact"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Submit News


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: 
  hero_description: 


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  number_posts: 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  tags:
    - tag: "news"
    - tag: "spotlight"
    - tag: "trends"
    - tag: "technology"
    - tag: "tutorials"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.


#-------------------------------
# Authors Section Settings
authors_section:
  enable: true
  section_title: Meet our authors


#-------------------------------
# Footer Settings
footer_description: Your source for the latest in vj technology and culture.


# Social Links
social:
- {icon: "twitter", link: "https://twitter.com/vjsmag"}
- {icon: "facebook", link: "https://facebook.com/vjsmag"}
- {icon: "instagram", link: "https://instagram.com/vjsmag"}
- {icon: "linkedin", link: "https://linkedin.com/company/vjsmag"}
- {icon: "pinterest", link: "https://pinterest.com/vjsmag/"}
- {icon: "youtube", link: "https://www.youtube.com/user/vjstv"}
- {icon: "vimeo", link: "https://vimeo.com/vjstv"}
- {icon: "feed", link: "https://www.vjsmag.com/feed"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: true
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp_identifier: https://vjsmag.us22.list-manage.com/subscribe?u=04b35b1905693c4daca7b592a&id=89e5d17e3e # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: vjsmag@gmail.com # Add your form_id
  description: We are always happy to hear from our customers, partners, and visitors. Whether you have a question, comment, suggestion, or just want to say hello, we are here to listen. Our dedicated team is ready to assist you with any inquiries or concerns you may have. Please don’t hesitate to reach out to us using the form provided on this page, or through the contact information listed below. We look forward to connecting with you! # Add a description of your form

# NOTE
# Danto theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id